### ISSUE TITLE
Update all laptops to Eclipse 2018 Photon

### ISSUE THREAD

**Issue by cmarley3-14** [garykac/amhs-robotics-4681#1]

**Comment by Team4681** [comment]
~~And Use JDK Java SE 11.0.2(LTS)
https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html~~

**Comment by Team4681** [comment]
~~Link with instructions for installing Eclipse:
https://www.ntu.edu.sg/home/ehchua/programming/howto/EclipseJava_HowTo.html~~

(Eclipse is not supported this year)

**Comment by amhsrobotics4681** [comment]
~~Link for setting up a RoboRio Java project:
http://www.team2648.com/java.html~~

**Comment by Team4681** [comment]
https://github.com/wpilibsuite/allwpilib/releases

**Comment by cmarley3-14** [comment]
https://wpilib.screenstepslive.com/s/4485
https://wpilib.screenstepslive.com/s/currentCS/m/java

Use this to move existing Eclipse programs into VSCode:
    https://wpilib.screenstepslive.com/s/currentCS/m/java/l/1027508-importing-an-eclipse-project-into-vs-code

A how-to on creating FRC Robot programs:
    https://wpilib.screenstepslive.com/s/currentCS/m/java/l/1027062-creating-a-robot-program

**Comment by garykac** [comment]
The main setup page for FRC Java is
https://wpilib.screenstepslive.com/s/currentCS/m/java

(given above, but repeated here so it doesn't get lost in the links)

**Comment by Team4681** [comment]
Done. VScode set up complete
