### ISSUE TITLE
Polarity of yellow cord for ultrasonic sensor

### ISSUE THREAD

**Issue by amhsrobotics4681** [garykac/amhs-robotics-4681#13]
https://www.northcoastelectric.com/Allen-Bradley-873M-D18AV300-D4/P1754542
Guide Manuals
Specification sheet
2nd Page

**Comment by garykac** [comment]
Direct link to data sheet: https://www.ideadigitalcontent.com/files/11994/ID-SPE-v1-873m-in001_en-p.pdf

**Comment by garykac** [comment]
This information has been copied over into issue #4, which is already tracking the Ultrasonic work item.
