### ISSUE TITLE
Example Code for Switches

### ISSUE THREAD

**Issue by amhsrobotics4681** [garykac/amhs-robotics-4681#14]
Java

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SampleRobot;
import edu.wpi.first.wpilibj.Timer;

public class RobotTemplate extends SampleRobot {
	
	DigitalInput limitSwitch;
	
	public void robotInit() {
		limitSwitch = new DigitalInput(1);
	}
	
	public void operatorControl() {
		// more code here
		while (limitSwitch.get()) {
			//whatever you want to happen
		}
	}
}

**Comment by Team4681** [comment]
https://media.readthedocs.org/pdf/frc-pdr/latest/frc-pdr.pdf
