### ISSUE TITLE
Button Layouts

### ISSUE THREAD

**Issue by amhsrobotics4681** [garykac/amhs-robotics-4681#15]
A Button (Ball Intake) **(2)**
B Button (Ball Outtake) **(3)**
X Button (Suction On) **(1)**
Y Button (Suction Off) **(4)**
Both Joy Sticks (Driving Related) **(AXIS))**
Climbing End Game (Start) **(10)**
Up Arrow (Ball Elevator Up 1 Level) **(TOP)**
Down Arrow (Ball Elevator Down 1 Level) **(DOWN)**
Left Arrow (Ball Elevator All the Way Down) **(LEFT)**
Right Trigger (Turn 90 Degrees Right) **(8)**
Left Trigger (Turn 90 Degrees Left) **(7)**

**Comment by RyanDecker123** [comment]
moved to Wiki

**Comment by RyanDecker123** [comment]
This really isnt a problem
