### ISSUE TITLE
Sucker needs to extend to grab hatch

### ISSUE THREAD

**Issue by garykac** [garykac/amhs-robotics-4681#32]
(extracted from issue #31)

Code should be written but has not been tested

**Comment by cmarley3-14** [comment]
https://github.com/garykac/amhs-robotics-4681/blob/c23548da530a701cca6068251ccac26d334a6a57/workspace/2019%20DeepSpace/src/main/java/frc/robot/Sucker.java#L24-L31

The suck function sucks and unsucks  
The extend function extends and retracts

That's a confusing way to write it, but it works.
